name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Configure and Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Package Artifacts
        run: |
          cd
